# Generated by Django 4.2.5 on 2023-10-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('shipping_address', models.TextField()),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('subtotal', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('payment received', 'payment received'), ('order in progress', 'order in progress'), ('order canceled', 'order canceled'), ('order shipped', 'order shipped'), ('order completed', 'order completed')], max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('paystack', 'paystack'), ('transefer', 'transefer')], default='paystack', max_length=50, null=True)),
                ('payment_complete', models.BooleanField(default=False)),
                ('ref', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
    ]
