# Generated by Django 4.2.5 on 2023-10-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('payment received', 'payment received'), ('order in progress', 'order in progress'), ('order canceled', 'order canceled'), ('order shipped', 'order shipped'), ('order completed', 'order completed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
